# Alembic configuration file for banking-demo

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(asctime)s_%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.datetime.now(datetime.timezone(datetime.timedelta(seconds=tz_offset)))
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in file_template
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure, based on the keys they are given
# in the [loggers] section.
# Keys should be names of loggers, such as that used
# by the logging module by name of the logger specified in
# the script.
# Keys represent logging.getLogger(args[0]) calls
# [loggers]
# keys = sqlalchemy.engine,sqlalchemy.pool

# [handlers]
# keys = console

# [formatters]
# keys = generic

# [logger_root]
# level = WARN
# handlers = console
# qualname =

# [logger_sqlalchemy.engine]
# level = INFO
# handlers =
# qualname = sqlalchemy.engine

# [logger_sqlalchemy.pool]
# level = INFO
# handlers =
# qualname = sqlalchemy.pool

# [handler_console]
# class = StreamHandler
# args = (sys.stderr,)
# level = NOTSET
# formatter = generic

# [formatter_generic]
# format = %%(levelname)-5.5s [%%(name)s] %%(message)s
# datefmt = %%(asctime)s

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = sqlite:////data/sqlite/banking.db

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%(asctime)s
